### ISSUE TITLE
Support for Retrospective Tax Calculations for Individuals

### ISSUE THREAD

**Issue by orbiri** [hadeutscher/HaSalary#1]
The HaSalary repository currently supports tax calculations based on the current tax year, but individuals may need to calculate their taxes retrospectively for previous years. Therefore, I would like to request the addition of a feature that supports retrospective tax calculations for individuals.

This feature could be implemented by allowing users to select a previous tax year and input the tax rates and thresholds for that year. The code would then use these parameters to calculate the taxes owed for the selected year.

I believe that adding support for retrospective tax calculations would greatly enhance the usefulness of this repository for individuals who want to validate their tax calculations for previous years. This feature would also help users ensure that their tax calculations are accurate and up-to-date.

Thank you for considering my feature request!

(Disclaimer: This feature request was written by ChatGPT)

**Comment by hadeutscher** [comment]
Tracking ticket: https://hadeutscher.notion.site/Update-HaSalary-for-2023-54a1069c24c3465a8e3f69e53135b8a9

**Comment by orbiri-ns** [comment]
Thank you!!!!!
